apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "teletrace.fullname" . }}
  labels:
    {{- include "teletrace.labels" . | nindent 4 }}
data:
  collector-config.yaml: |
    {{- .Values.collectorConfig | nindent 4 }}
