apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lupa.fullname" . }}
  labels:
    {{- include "lupa.labels" . | nindent 4 }}
data:
  collector-config.yaml: |
    {{- toYaml .Values.collectorConfig | nindent 4 }}
