apiVersion: v1
kind: Service
metadata:
  name: {{ include "teletrace.fullname" . }}
  labels:
    {{- include "teletrace.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    {{- range $key, $port := .Values.ports }}
    {{- if $port.enabled }}
    - name: {{ $key }}
      port: {{ $port.servicePort }}
      targetPort: {{ $port.containerPort }}
      protocol: {{ $port.protocol }}
    {{- end }}
    {{- end }}
  selector:
    {{- include "teletrace.selectorLabels" . | nindent 4 }}
